export interface MusicInfo {
  id?: string,
  fileId?: string,
  type?: string,
  fileName?: string,
  title?: string,
  artist?: string,
  album?: string,
  year?: string,
  trackNumber?: string,
  coverInfo?: string,
  lyrics?: string,
  lyricsLength?: number,
  trackLength?: string,
  size?: number,
  bitrate?: string,
  format?: string,
  newItem?: boolean,
  updateColumns?: string[],
}
